In [1]:
!pip install torch

In [1]:
import torch 
vector= torch.tensor([2,3])

In [2]:
vector.ndim

1

In [3]:
 ### Matrix multiplication  or dot product
torch.matmul(torch.tensor([2,3,4]),torch.tensor([1,2,3]))

tensor(20)

## Reshaping , squeezing, unsqueezing the tensors 

* Reshaping

* view -  Return a view of the input tensor of certain shape but keep the same memory as the original tensor

* Stacking - Combine the multiple tensors on top of each other (vstack ) or side by side (hstack)

* Squeeze - Removes all '1' dimension d=from a tensor 

* Permute

In [4]:
x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [5]:
x_1 = x.reshape(1, 9)
x_1

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
x_2 = x.reshape(9, 1)
x_2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [7]:
## View 
z= x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
## Changing the z will also change the x because they share same memory 
z[0][:]=5
z= torch.arange(1., 10.)
z, x

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [19]:
# Stack 
x_stack = torch.stack([x,x,x], dim=1)  # 0,1 only dimensions compatible for tensor x
x_stack, x_stack.shape

(tensor([[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]),
 torch.Size([9, 3]))

In [10]:
# Sqeeze  
y = torch.squeeze(x_1)  ## All single dimensions have been removed
x_1, y , y.shape

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 torch.Size([9]))

In [22]:
# Unsqueeze 
u= x.unsqueeze(dim=1) ## Adds 1 at the given dim in the shape of the tensor
u, u.shape

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 torch.Size([9, 1]))

In [12]:
# permute - creates a view of the tensor 
original = torch.rand(size=(224,224,3))   ## HEight width and the color channels 
## permute will change the dimension of the tensor 
permuted= original.permute(2,0,1)

In [13]:
permuted.shape

torch.Size([3, 224, 224])

In [14]:
## from tensor to numpy   `tensor.numpy()`
## from numpy to tensor    `torch.from_numpy()`

#### Reproducibility of Random data

To reduce the randomness in neural networks we use Random Seed

Random but reproducible tensors

In [15]:
import torch 

num1=torch.rand(2,3)
num2=torch.rand(2,3)

print(num1)
print(num2)

tensor([[0.9570, 0.9497, 0.3080],
        [0.3976, 0.1194, 0.1982]])
tensor([[0.1700, 0.8224, 0.7758],
        [0.2016, 0.1275, 0.8210]])


In [16]:
## now using random Seed
torch.manual_seed(42)
tensor1=torch.rand(4,3)

torch.manual_seed(42)
tensor2=torch.rand(4,3)
print(tensor1)
print(tensor2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [17]:
## See the random results are the same!!!

## Neural Network Introduction

In [8]:
import numpy as np

In [7]:
arr= np.array()

[[[1], [2]], 5]

In [12]:
arr = np.array([[[1], [4]], [[1], [4]]])

In [13]:
arr.shape

(2, 2, 1)

In [17]:
np.squeeze(arr)

array([[1, 4],
       [1, 4]])